/**
 * A PulseMap describes the inherent structure of a single recording.
 * One canonical map per recording; maps are source-agnostic and never
 * modified by journeys or playback contexts.
 */
export interface PulseMap {
	/** Schema version (semver). */
	version: string;

	/** MusicBrainz recording ID. Canonical identifier for the recording. */
	id: string;

	/** Total duration of the recording in milliseconds. */
	duration_ms: number;

	/** Chromaprint audio fingerprint data, generated by fpcalc. */
	fingerprint?: Fingerprint;

	/** Descriptive metadata for display and search. */
	metadata?: MapMetadata;

	/** Known platforms where this recording can be played. */
	playback?: PlaybackTarget[];

	/** Time-synced lyric lines. */
	lyrics?: LyricLine[];

	/** Time-synced chord events. */
	chords?: ChordEvent[];

	/** Beat events with tempo, time signature, and downbeat tracking. */
	beats?: BeatEvent[];

	/** Labeled structural sections (verse, chorus, bridge, etc.). */
	sections?: Section[];

	/** Associated MIDI transcription files (e.g. separate files for drums, bass, melody). */
	midi?: MidiReference[];

	/**
	 * Provenance metadata for analyzed fields.
	 *
	 * Keys are map field names ("beats", "chords", "lyrics", "midi",
	 * "fingerprint", "sections"). Tracks which tool produced each field,
	 * enabling quality filtering, selective re-analysis, and migration
	 * when tools improve.
	 */
	analysis?: Record<string, AnalysisProvenance>;
}

/**
 * Descriptive metadata for display and search.
 *
 * Typed fields cover common display needs. For additional metadata,
 * use `extra` with keys following MusicBrainz Picard tag naming
 * conventions (e.g. "isrc", "date", "genre", "tracknumber").
 *
 * Fields like `key` and `tempo` represent the predominant or starting
 * value for the recording. Songs with key changes or tempo variations
 * should be analyzed via the `chords` and `beats` event arrays for
 * precise tracking.
 */
export interface MapMetadata {
	title?: string;
	artist?: string;
	album?: string;

	/** Predominant key (e.g. "C major", "F# minor"). See `chords` for modulations. */
	key?: string;

	/** Predominant tempo in BPM. See `beats` for tempo variations. */
	tempo?: number;

	/** Time signature as a string (e.g. "4/4", "3/4", "6/8"). */
	time_signature?: string;

	/** Additional metadata. Keys follow MusicBrainz Picard tag conventions. */
	extra?: Record<string, string | number | string[]>;
}

/**
 * Chromaprint audio fingerprint data.
 *
 * Generated by fpcalc. The `algorithm` version and `duration` of the
 * source audio are required for reproducible matching — different
 * algorithm versions or audio lengths produce different fingerprints.
 */
export interface Fingerprint {
	/** Base64-encoded Chromaprint fingerprint string. */
	chromaprint: string;

	/** Chromaprint algorithm version used to generate the fingerprint. */
	algorithm: number;

	/** Duration of the source audio in milliseconds (as seen by fpcalc). */
	duration: number;
}

/**
 * A known platform where this recording can be played.
 * Each target represents a specific instance (a YouTube video,
 * a Spotify track) — not an environmental capability like
 * local file playback or microphone capture.
 */
export interface PlaybackTarget {
	/** Platform identifier. */
	platform: "youtube" | "spotify" | "soundcloud" | "bandcamp" | (string & {});

	/** URI for this instance (any scheme: https, ipfs, magnet, spotify, etc.). */
	uri?: string;

	/** Platform-specific ID (e.g. YouTube video ID, Spotify track ID). */
	id?: string;

	/** What this platform's adapter can do. */
	capabilities: PlaybackCapabilities;

	/** ISO 8601 date when this target was added or last verified. */
	added?: string;
}

/**
 * Declares what a playback adapter can control.
 *
 * Boolean capabilities are present when the adapter supports them.
 * Omitted or false means unsupported. `rate` uses a discriminated
 * form: "continuous" for arbitrary rate control, or a number array
 * for platforms that only offer fixed speed options (e.g. YouTube
 * offers [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2]).
 */
export interface PlaybackCapabilities {
	/** Adapter can start playback programmatically. */
	play?: boolean;

	/** Adapter can pause playback programmatically. */
	pause?: boolean;

	/** Adapter can seek to an arbitrary position. */
	seek?: boolean;

	/** Adapter can set the playback position programmatically (for journey authoring). */
	setPosition?: boolean;

	/** Adapter can report current playback position. */
	getPosition?: boolean;

	/** Adapter can control playback speed. */
	rate?: "continuous" | number[];

	/** Adapter can control volume. */
	volume?: boolean;

	/** Adapter can mute/unmute. */
	mute?: boolean;
}

/**
 * Reference to an associated MIDI transcription file.
 *
 * Maps do not embed MIDI data — a .mid file is the right container.
 * The map stores enough to identify and synchronize the file.
 *
 * `sha256` is a hash of the raw .mid file bytes, serving as a
 * content-addressable identifier. A player with a MIDI file computes
 * the hash to verify it matches what the map expects.
 */
export interface MidiReference {
	/** SHA-256 hash of the .mid file. Canonical identifier. */
	sha256: string;

	/** Duration of the MIDI file in milliseconds, for quick validation. */
	duration_ms: number;

	/** Timing offset in ms if MIDI doesn't start at map t=0. */
	offset_ms?: number;

	/** URI hint for where to obtain the file (any scheme). Not authoritative. */
	uri?: string;

	/** Track index-to-label mapping (e.g. 0: "melody", 1: "bass"). */
	tracks?: MidiTrack[];
}

export interface MidiTrack {
	index: number;
	label: string;
}

/**
 * A single beat event.
 *
 * Every beat in the recording gets an entry. `bpm` and `time_sig`
 * are sparse change events: they appear on the beat where the value
 * changes (the first beat must set both). Consumers carry forward
 * the last-seen value for beats that omit them.
 */
export interface BeatEvent {
	/** Beat time in milliseconds. */
	t: number;

	/** Whether this beat is a downbeat (first beat of a measure). */
	downbeat: boolean;

	/** BPM at this beat. Only present when the tempo changes (or on the first beat). */
	bpm?: number;

	/** Time signature at this beat. Only present when it changes (or on the first beat). */
	time_sig?: string;
}

/** Provenance metadata for an analyzed map field. */
export interface AnalysisProvenance {
	/** Tool or method that produced this field (e.g. "essentia", "lrclib", "basic-pitch"). */
	tool: string;

	/** Version of the tool. */
	version?: string;

	/** ISO 8601 date when the analysis was performed. */
	date?: string;

	/** Whether the field has been manually reviewed or corrected. */
	manual?: boolean;
}

/** A single time-synced lyric line. */
export interface LyricLine {
	/** Start time in milliseconds. */
	t: number;

	/** Lyric text for this line. */
	text: string;

	/** End time in ms. If omitted, infer from the next line's start time. */
	end?: number;
}

/** A chord event at a point in time. */
export interface ChordEvent {
	/** Start time in milliseconds. */
	t: number;

	/**
	 * Chord name using standard notation (e.g. "Cmaj7", "F#m", "Bb/D").
	 * Transposition is applied at render time, not in the map.
	 */
	chord: string;

	/** End time in ms. If omitted, infer from the next chord event's start time. */
	end?: number;
}

/**
 * Recommended section types. Use these where they fit; ad-hoc strings
 * are valid for structures that don't map to standard song form
 * (e.g. podcast chapters, theatrical cues).
 */
export type SectionType =
	| "intro"
	| "verse"
	| "pre-chorus"
	| "chorus"
	| "bridge"
	| "solo"
	| "interlude"
	| "outro"
	| "coda"
	| (string & {});

/** A structural section of the recording. */
export interface Section {
	/** Start time in milliseconds. */
	t: number;

	/** Structural type (e.g. "verse", "chorus", "solo"). */
	type: SectionType;

	/** Freeform label for display (e.g. "Guitar Solo", "Chapter 3: The River"). */
	label?: string;

	/** End time in milliseconds. */
	end: number;
}
